const clients = [
  {
    client: 'u011766',
    address: {
      address: 'улица Артамонова, 16',
      flats: 140,
      entrances: 4,
      floors: '9',
    },
    gender: 'M',
    age: '60-69',
  },
  {
    client: 'u008046',
    address: {
      address: 'улица Карла Маркса, 98',
      flats: 142,
      entrances: 4,
      floors: '10  и 12',
    },
    gender: 'M',
    age: '60-69',
  },
  {
    client: 'u008053',
    address: {
      address: 'улица 45 Стрелковой Дивизии, 285',
      flats: 141,
      entrances: 4,
      floors: '9',
    },
    gender: 'M',
    age: '40-49',
  },
  {
    client: 'u003790',
    address: {
      address: 'улица Юлюса Янониса, 5',
      flats: 139,
      entrances: 3,
      floors: '9',
    },
    gender: 'Ж',
    age: '40-49',
  },
  {
    client: 'u006932',
    address: {
      address: 'улица Беговая, 219/3',
      flats: 340,
      entrances: 4,
      floors: '17',
    },
    gender: 'M',
    age: '40-49',
  },
  {
    client: 'u005115',
    address: {
      address: 'улица Беговая, 168',
      flats: 216,
      entrances: 6,
      floors: '9',
    },
    gender: 'Ж',
    age: '30-39',
  },
  {
    client: 'u013376',
    address: {
      address: 'улица Берег реки Дон, 29-е',
      flats: 208,
      entrances: 5,
      floors: '10',
    },
    gender: 'M',
    age: '30-39',
  },
  {
    client: 'u013854',
    address: {
      address: 'улица Острогожская, 170/4',
      flats: 340,
      entrances: 2,
      floors: '17',
    },
    gender: 'Ж',
    age: '30-39',
  },
  {
    client: 'u011766',
    address: {
      address: 'улица Артамонова, 16',
      flats: 140,
      entrances: 4,
      floors: '9',
    },
    gender: 'M',
    age: '60-69',
  },
  {
    client: 'u008046',
    address: {
      address: 'улица Карла Маркса, 98',
      flats: 142,
      entrances: 4,
      floors: '10  и 12',
    },
    gender: 'M',
    age: '60-69',
  },
  {
    client: 'u008053',
    address: {
      address: 'улица 45 Стрелковой Дивизии, 285',
      flats: 141,
      entrances: 4,
      floors: '9',
    },
    gender: 'M',
    age: '40-49',
  },
  {
    client: 'u003790',
    address: {
      address: 'улица Юлюса Янониса, 5',
      flats: 139,
      entrances: 3,
      floors: '9',
    },
    gender: 'Ж',
    age: '40-49',
  },
  {
    client: 'u006932',
    address: {
      address: 'улица Беговая, 219/3',
      flats: 340,
      entrances: 4,
      floors: '17',
    },
    gender: 'M',
    age: '40-49',
  },
  {
    client: 'u005115',
    address: {
      address: 'улица Беговая, 168',
      flats: 216,
      entrances: 6,
      floors: '9',
    },
    gender: 'Ж',
    age: '30-39',
  },
  {
    client: 'u013376',
    address: {
      address: 'улица Берег реки Дон, 29-е',
      flats: 208,
      entrances: 5,
      floors: '10',
    },
    gender: 'M',
    age: '30-39',
  },
  {
    client: 'u013854',
    address: {
      address: 'улица Острогожская, 170/4',
      flats: 340,
      entrances: 2,
      floors: '17',
    },
    gender: 'Ж',
    age: '30-39',
  },
  {
    client: 'u006951',
    address: {
      address: 'проспект Патриотов, 38-а',
      flats: 157,
      entrances: 4,
      floors: '10',
    },
    gender: 'Ж',
    age: '40-49',
  },
  {
    client: 'u002594',
    address: {
      address: 'улица Морозова, 10',
      flats: 135,
      entrances: 4,
      floors: '9',
    },
    gender: 'Ж',
    age: '40-49',
  },
  {
    client: 'u004071',
    address: {
      address: 'улица Героев Стратосферы, 5',
      flats: 50,
      entrances: 7,
      floors: '4',
    },
    gender: 'M',
    age: '30-39',
  },
  {
    client: 'u006255',
    address: {
      address: 'улица 20-летия Октября, 64',
      flats: 125,
      entrances: 4,
      floors: '8-16',
    },
    gender: 'Ж',
    age: '60-69',
  },
  {
    client: 'u002147',
    address: {
      address: 'улица Кривошеина, 13/13',
      flats: 744,
      entrances: 6,
      floors: '17-18',
    },
    gender: 'M',
    age: '30-39',
  },
  {
    client: 'u013553',
    address: {
      address: 'улица Старых Большевиков, 92-а',
      flats: 255,
      entrances: 6,
      floors: '10',
    },
    gender: 'M',
    age: '40-49',
  },
  {
    client: 'u006275',
    address: {
      address: 'улица 9 Января, 48',
      flats: 50,
      entrances: 1,
      floors: '4',
    },
    gender: 'Ж',
    age: '60-69',
  },
  {
    client: 'u013850',
    address: {
      address: 'бульвар Олимпийский, 14',
      flats: 1600,
      entrances: 12,
      floors: '17',
    },
    gender: 'Ж',
    age: '30-39',
  },
  {
    client: 'u010837',
    address: {
      address: 'бульвар Победы, 50',
      flats: 365,
      entrances: 4,
      floors: '1,2,3=17;4=18;.',
    },
    gender: 'M',
    age: '50-59',
  },
  {
    client: 'u010502',
    address: {
      address: 'улица Космонавта Комарова, 13',
      flats: 130,
      entrances: 4,
      floors: '9',
    },
    gender: 'M',
    age: '50-59',
  },
  {
    client: 'u003935',
    address: {
      address: 'улица Миронова, 47',
      flats: 460,
      entrances: 6,
      floors: '16',
    },
    gender: 'M',
    age: '40-49',
  },
  {
    client: 'u002390',
    address: {
      address: 'улица Остроухова, 1',
      flats: 56,
      entrances: 4,
      floors: '5',
    },
    gender: 'Ж',
    age: '40-49',
  },
  {
    client: 'u010040',
    address: {
      address: 'Московский проспект, 90 корпус 1',
      flats: 1163,
      entrances: 8,
      floors: '17',
    },
    gender: 'M',
    age: '70-79',
  },
  {
    client: 'u001083',
    address: {
      address: 'улица Фёдора Тютчева, 93/5',
      flats: 340,
      entrances: 4,
      floors: '17',
    },
    gender: 'Ж',
    age: '30-39',
  },
  {
    client: 'u002593',
    address: {
      address: 'улица Владимира Невского, 1-а',
      flats: 210,
      entrances: 6,
      floors: '9',
    },
    gender: 'M',
    age: '40-49',
  },
  {
    client: 'u002478',
    address: {
      address: 'бульвар Победы, 51-а',
      flats: 633,
      entrances: 14,
      floors: '7,10,14 -16 этажей, остальные 10 этажей',
    },
    gender: 'M',
    age: '60-69',
  },
  {
    client: 'u004375',
    address: {
      address: 'улица Карла Маркса, 49',
      flats: 110,
      entrances: 8,
      floors: '5',
    },
    gender: 'M',
    age: '60-69',
  },
  {
    client: 'u010456',
    address: {
      address: 'улица Иркутская, 9',
      flats: 82,
      entrances: 1,
      floors: '12',
    },
    gender: 'Ж',
    age: '50-59',
  },
  {
    client: 'u011392',
    address: {
      address: 'переулок Павловский, 64-в',
      flats: 179,
      entrances: 5,
      floors: '9',
    },
    gender: 'M',
    age: '40-49',
  },
  {
    client: 'u005436',
    address: {
      address: 'улица Героев Сибиряков, 52',
      flats: 120,
      entrances: 8,
      floors: '5',
    },
    gender: 'M',
    age: '50-59',
  },
  {
    client: 'u005565',
    address: {
      address: 'улица Путиловская, 5',
      flats: 143,
      entrances: 4,
      floors: '9',
    },
    gender: 'M',
    age: '40-49',
  },
  {
    client: 'u014298',
    address: {
      address: 'улица Острогожская, 164/2',
      flats: 440,
      entrances: 8,
      floors: '12',
    },
    gender: 'M',
    age: '40-49',
  },
  {
    client: 'u001613',
    address: {
      address: 'улица Кривошеина, 13/13',
      flats: 744,
      entrances: 6,
      floors: '17-18',
    },
    gender: 'M',
    age: '30-39',
  },
  {
    client: 'u005824',
    address: {
      address: 'улица Южно-Моравская, 33',
      flats: 217,
      entrances: 1,
      floors: '9',
    },
    gender: 'Ж',
    age: '60-69',
  },
];

export default clients;
